title: Stackbit App Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: full-width
style: minimal
palette: blue
mode: light
base_font: sans-serif
header:
  title: App
  logo: images/J4FLogo1x.png
  logo_alt: App logo
  has_primary_nav: true
  primary_nav_links:
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - label: Figma Comunity (soon)
      url: /
      style: primary
  has_anncmnt: true
  anncmnt_content: >-
    Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
    More](/pricing/)**
  anncmnt_align: left
  anncmnt_is_home_only: true
  anncmnt_has_close: true
  anncmnt_id: new-features
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://diligent-hickory-33f37.netlify.app'
